CREATE TABLE HOTEL (id INT PRIMARY KEY, name VARCHAR (255), description VARCHAR (255), brand VARCHAR (255));
CREATE TABLE ADDRESS (id INT PRIMARY KEY, houseNumber INT, street VARCHAR (255), city VARCHAR (255), country VARCHAR (255), postCode VARCHAR (255));
CREATE TABLE CONTACTS (id INT PRIMARY KEY, phone VARCHAR (255), email VARCHAR (255));
CREATE TABLE ARRIVALTIME (id INT PRIMARY KEY, checkIn VARCHAR (255), checkOut VARCHAR (255));
CREATE TABLE AMENITIES (id INT PRIMARY KEY, amenities VARCHAR (255));
